### ISSUE TITLE
Does not support *~ pattern?

### ISSUE THREAD

**Issue by arichiardi** [hcarvalhoalves/duplicity#3]
I have a big list of exclusions and one of it is: `--exclude *~`.
When I start duplicity though, I receive:

```
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1546, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1540, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1375, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1131, in ProcessCommandLine
    set_selection()
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 969, in set_selection
    sel.ParseArgs(select_opts, select_files)
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 250, in ParseArgs
    self.add_selection_func(self.glob_get_sf(arg, 0))
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 436, in glob_get_sf
    sel_func = self.glob_get_normal_sf(glob_str, include)
  File "/usr/lib/python2.7/dist-packages/duplicity/selection.py", line 548, in glob_get_normal_sf
    raise FilePrefixError(glob_str)
FilePrefixError: *~
```

What can be the issue?

**Comment by arichiardi** [comment]
Sorry, I see this one has been abandoned...
